name: Maven Verify

on:
  push: # Ignore releases and main dev branch
    tags-ignore:
      - 'v*'
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  INSTRUCTOR_USER: "instructor_e2e"
  INSTRUCTOR_PASSWORD: ${{ secrets.INSTRUCTOR_PASSWORD }}
  STUDENT_USER: "student_e2e"
  ARTEMIS_URL: "https://artemis-test.ipd.kit.edu"
  COURSE_ID: "4"
  PROGRAMMING_EXERCISE_ID: "14"

jobs:
  verify:
    uses: kit-sdq/actions/.github/workflows/maven.yml@main
    with:
      deploy: false
    secrets:
      OSSRH_USER: ""
      OSSRH_TOKEN: ""
      GPG_KEY: ""
